import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar/Navbar";
import { promises as fs } from "fs";
import path from "path";
import Footer from "@/component/footer/Footer";
import Providers from "./lib/providers/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const filePath = path.join(process.cwd(), "public", "friends.json");
  const fileContent = await fs.readFile(filePath, "utf-8");
  const { friends } = JSON.parse(fileContent);

  return (
    <html lang="en" className={`${geistSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Providers friends={friends}>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}